"""Generate each environment's lock from the project manifest.

Four requirements files pin three mutually incompatible model stacks,
and until now every one of them was a full `pip freeze`: a transitive
closure with no record of which packages were ever asked for. Nothing
said that `tensorboard` and `datasets` were left over from a training
phase this project no longer has, or that 14 CUDA 12 packages in the
DiffusionGemma environment were orphaned by an in-place torch upgrade.
Nothing recorded the Python version, the index, or a hash.

So the manifest under `[tool.diffusion-llm]` holds the direct
requirements, and this script produces the locks. The split is the
point: the manifest answers "what did we ask for" and is short enough
to read, while the lock answers "what did that produce" and is not
meant to be read at all.

Usage::

    .venv/bin/python scripts/lock_environments.py            # check
    .venv/bin/python scripts/lock_environments.py --update   # write

Checking is offline and needs no resolver. Each lock carries a digest
of the manifest entry that produced it, so a requirements list edited
without regenerating is caught by recomputing that digest, which is
what makes this safe to run in the test suite. Only `--update` reaches
the network.

Regeneration is deliberately constrained by the lock it replaces, so
it cannot change a version. That is not politeness: every saved run
records its library versions, and a resolver that helpfully upgraded
torch would change what the models do while looking like a tidying
commit. Upgrading is a separate decision, made by removing the
constraint on purpose.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "pyproject.toml"

# The header this script writes above every generated lock. Comments,
# so pip and uv ignore them, and the last line is the drift guard.
GENERATED_BY = "# Generated by scripts/lock_environments.py."
DO_NOT_EDIT = "# Do not edit by hand; edit pyproject.toml instead."
DIGEST_PREFIX = "# manifest-digest: "

# Long enough that a collision is not a concern, short enough to read.
DIGEST_CHARS = 32

assert DIGEST_CHARS > 0, "a digest needs characters"
assert DIGEST_PREFIX.startswith("#"), "the header must be a comment"


def load_environments() -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """The manifest's shared settings and its environments.

    Returns the two separately because they are used differently: the
    shared half goes into every digest, so changing the Python version
    invalidates all four locks at once, which is correct.
    """
    data = tomllib.loads(
        MANIFEST_PATH.read_text(encoding="utf-8")
    )
    config = data["tool"]["diffusion-llm"]
    shared = {
        "python-version": config["python-version"],
        "index": config["index"],
    }
    environments = config["environments"]
    assert environments, "the manifest declares no environments"
    return shared, environments


def manifest_digest(
    shared: Dict[str, Any], environment: Dict[str, Any]
) -> str:
    """A digest over everything that decides a lock's content.

    Canonical JSON with sorted keys rather than the raw TOML text, so
    reordering a requirements list or reflowing a comment does not
    invalidate a lock that would compile identically. What must
    invalidate it is a changed requirement, Python version or index,
    and those are exactly what goes in.
    """
    payload = {
        "python-version": shared["python-version"],
        "index": shared["index"],
        "requirements": sorted(environment["requirements"]),
        "extends": environment.get("extends"),
    }
    encoded = json.dumps(
        payload, sort_keys=True, separators=(",", ":")
    )
    full = hashlib.sha256(encoded.encode("utf-8")).hexdigest()
    return full[:DIGEST_CHARS]


def header_for(
    name: str,
    shared: Dict[str, Any],
    environment: Dict[str, Any],
) -> List[str]:
    """The comment block stamped above a generated lock."""
    lines = [
        GENERATED_BY,
        DO_NOT_EDIT,
        f"# environment: {name}",
        f"# description: {environment['description']}",
        f"# python-version: {shared['python-version']}",
        f"# index: {shared['index']}",
    ]
    if environment.get("extends"):
        lines.append(
            f"# extends: {environment['extends']}"
            " (installed into that environment)"
        )
    lines.append(
        DIGEST_PREFIX + manifest_digest(shared, environment)
    )
    return lines


def recorded_digest(lock_text: str) -> Optional[str]:
    """The digest a lock claims, or None if it claims none.

    None covers an ungenerated lock as well as a malformed one. Both
    mean the same thing to the caller, which is that this file cannot
    vouch for itself.
    """
    for line in lock_text.splitlines():
        if line.startswith(DIGEST_PREFIX):
            value = line[len(DIGEST_PREFIX):].strip()
            return value or None
        if line and not line.startswith("#"):
            # Past the header; a digest below it would not be one.
            return None
    return None


def compile_lock(
    name: str,
    shared: Dict[str, Any],
    environment: Dict[str, Any],
) -> str:
    """Resolve one environment, returning the lock's body.

    The existing lock is passed as a constraint so the resolution
    cannot move a version. On a first-ever lock there is nothing to
    constrain against, and the resolver is free; that is the one case
    where this script can change what installs, and it says so.
    """
    lock_path = REPO_ROOT / environment["lock"]
    with tempfile.TemporaryDirectory() as work:
        source = Path(work) / f"{name}.in"
        source.write_text(
            "\n".join(environment["requirements"]) + "\n",
            encoding="utf-8",
        )
        command = [
            str(REPO_ROOT / ".venv" / "bin" / "uv"),
            "pip",
            "compile",
            str(source),
            "--python-version",
            str(shared["python-version"]),
            "--index-url",
            str(shared["index"]),
            "--generate-hashes",
            "--no-header",
            "--quiet",
        ]
        if lock_path.is_file():
            command.extend(["--constraint", str(lock_path)])
        else:
            print(
                f"  {name}: no existing lock to constrain against;"
                " the resolver is choosing versions",
                file=sys.stderr,
            )
        finished = subprocess.run(
            command,
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
    if finished.returncode != 0:
        raise RuntimeError(
            f"resolving {name} failed:\n{finished.stderr}"
        )
    return finished.stdout


def render_lock(
    name: str,
    shared: Dict[str, Any],
    environment: Dict[str, Any],
    body: str,
    environments: Dict[str, Any],
) -> str:
    """Header, any include, then the resolved body.

    An overlay emits a real ``-r`` include of the environment it
    extends, not just the header note. The desktop file has always
    been installable on its own, and a generated file that recorded
    the relationship in a comment while dropping the include would
    still install: it would just install a native window with no app
    underneath it.
    """
    lines = header_for(name, shared, environment)
    parent = environment.get("extends")
    if parent:
        parent_lock = environments[parent]["lock"]
        lines.extend(
            [
                "",
                f"# Everything {parent} has, so this file can be"
                " installed on its own.",
                f"-r {parent_lock}",
                "",
            ]
        )
    return "\n".join(lines) + "\n" + body


def pins_in(lock_text: str) -> Dict[str, str]:
    """Every ``name==version``, keyed by normalized name."""
    pins: Dict[str, str] = {}
    for line in lock_text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "==" not in stripped:
            continue
        head = stripped.split("==", 1)
        name = head[0].strip().lower().replace("_", "-")
        version = head[1].split()[0].strip().rstrip("\\").strip()
        if name and version:
            pins[name] = version
    return pins


def check() -> int:
    """Report locks that no longer match the manifest."""
    shared, environments = load_environments()
    stale: List[str] = []
    for name, environment in environments.items():
        lock_path = REPO_ROOT / environment["lock"]
        if not lock_path.is_file():
            stale.append(f"{name}: {environment['lock']} is missing")
            continue
        text = lock_path.read_text(encoding="utf-8")
        want = manifest_digest(shared, environment)
        have = recorded_digest(text)
        if have is None:
            stale.append(
                f"{name}: {environment['lock']} carries no digest,"
                " so it was not generated from the manifest"
            )
        elif have != want:
            stale.append(
                f"{name}: {environment['lock']} was generated from a"
                f" different manifest entry ({have} != {want})"
            )
    if stale:
        print("environment locks are out of date:")
        for line in stale:
            print(f"  {line}")
        print(
            "\nRun .venv/bin/python scripts/lock_environments.py"
            " --update to regenerate them."
        )
        return 1
    print(
        f"environment locks: {len(environments)} in step with"
        " the manifest."
    )
    return 0


def update() -> int:
    """Regenerate every lock, reporting what changed."""
    shared, environments = load_environments()
    for name, environment in environments.items():
        lock_path = REPO_ROOT / environment["lock"]
        before = (
            pins_in(lock_path.read_text(encoding="utf-8"))
            if lock_path.is_file()
            else {}
        )
        body = compile_lock(name, shared, environment)
        lock_path.write_text(
            render_lock(
                name, shared, environment, body, environments
            ),
            encoding="utf-8",
        )
        after = pins_in(lock_path.read_text(encoding="utf-8"))
        _report(name, before, after)
    return 0


def _report(
    name: str, before: Dict[str, str], after: Dict[str, str]
) -> None:
    """Say what regenerating did, in the terms that matter.

    Version changes first and separately, because they are the one
    outcome this script is built to avoid and the one a reader must
    not have to hunt for.
    """
    moved = sorted(
        key
        for key in before.keys() & after.keys()
        if before[key] != after[key]
    )
    dropped = sorted(before.keys() - after.keys())
    added = sorted(after.keys() - before.keys())
    print(f"{name}: {len(before)} -> {len(after)} pins")
    if moved:
        print("  versions changed (not the intent):")
        for key in moved:
            print(f"    {key}: {before[key]} -> {after[key]}")
    if dropped:
        print(f"  dropped ({len(dropped)}): {', '.join(dropped)}")
    if added:
        print(f"  added ({len(added)}): {', '.join(added)}")
    if not (moved or dropped or added):
        print("  unchanged")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate or verify the per-environment locks from the"
            " manifest in pyproject.toml."
        )
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help=(
            "Resolve and rewrite every lock. Needs the network;"
            " without it this only verifies, offline."
        ),
    )
    args = parser.parse_args()
    if args.update:
        return update()
    return check()


if __name__ == "__main__":
    sys.exit(main())
